wiki/urls.py
import combo.public.views
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('newpage/', views.new_page),
    path('ajax/newpage/', views.ajax_new_page),
    path('ajax/upload/', views.ajax_upload),
    path('ajax/make-public/<int:pk>/', views.make_public, name='wiki-make-public'),
    path('ajax/make-private/<int:pk>/', views.make_private, name='wiki-make-private'),
    re_path(
        r'^ajax/wiki/(?P<page_pk>\d+)/cell/(?P<cell_reference>[\w_-]+)/$',
        views.edit_wiki,
        name='wiki-edit',
    ),
    re_path(r'^', combo.public.views.page),
]

wiki/models.py
# django-panik-wiki - custom wiki
# Copyright (C) 2020  Frederic Peters
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import re
import urllib.parse

from combo.data.models import Page, TextCell
from django.db import models, transaction
from django.db.models.signals import post_save
from django.dispatch import receiver


class Interlink(models.Model):
    cell = models.ForeignKey(TextCell, on_delete=models.CASCADE)
    page = models.ForeignKey(Page, on_delete=models.SET_NULL, null=True)


@receiver(post_save, sender=TextCell)
def maintain_interlinks(sender, instance=None, **kwargs):
    with transaction.atomic():
        links = re.findall(r'href="(.*?)"', instance.text or '')
        Interlink.objects.filter(cell=instance).delete()
        for link in links:
            parsed = urllib.parse.urlparse(link)
            if parsed.netloc != '':
                continue
            if not parsed.path.startswith('/wiki/'):
                continue
            for page in Page.objects.filter(slug=parsed.path.strip('/').split('/')[-1]):
                if page.get_online_url() == parsed.path:
                    Interlink.objects.create(cell=instance, page=page)
                    break

wiki/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class NewPageForm(forms.Form):
    title = forms.CharField(label=_('Title'), required=True)

wiki/views.py
import os

from combo.data.models import Page, PageSnapshot, TextCell
from combo.manager.views import PageEditCellView
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage
from django.db.models import Q
from django.http import HttpResponseForbidden, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.edit import FormView
from sorl.thumbnail.shortcuts import get_thumbnail

from .forms import NewPageForm


class NewPageView(FormView):
    form_class = NewPageForm
    template_name = 'wiki/new_page.html'

    def form_valid(self, form):
        parent_wiki_page = Page.objects.get(slug='wiki', parent=None)
        self.new_page = Page(title=form.cleaned_data['title'], parent=parent_wiki_page, public=False)
        self.new_page.save()
        cell = TextCell(placeholder='content', page=self.new_page, order=0)
        cell.text = '<p>Nouvelle page, contenu à ajouter</p>'
        cell.save()
        return super().form_valid(form)

    def get_success_url(self):
        return self.new_page.get_online_url()


new_page = login_required(NewPageView.as_view())


@csrf_exempt
@login_required
def ajax_new_page(request, *args, **kwargs):
    parent_wiki_page = Page.objects.get(slug='wiki', parent=None)
    title = request.POST['title']
    slug = slugify(title)
    page = Page.objects.filter(Q(slug=slug) | Q(title=title)).first()
    if not page:
        page = Page(title=title, parent=parent_wiki_page, public=False)
        page.save()
        cell = TextCell(placeholder='content', page=page, order=0)
        cell.text = '<p>Nouvelle page, contenu à ajouter</p>'
        cell.save()
    return JsonResponse(
        {
            'url': page.get_online_url(),
            'request_id': request.POST['request_id'],
        }
    )


@csrf_exempt
@login_required
def ajax_upload(request, *args, **kwargs):
    upload = request.FILES['upload']
    upload_path = 'uploads'
    if os.path.splitext(upload.name.lower())[-1] in ('.jpg', '.jpeg', '.png', '.gif', '.svg'):
        upload_path = 'images'
    saved_path = default_storage.save('wiki/%s/%s' % (upload_path, upload.name), upload)
    url = '/media/' + saved_path
    response = {'url': url, 'filename': upload.name}
    if upload_path == 'images':
        if default_storage.size(saved_path) > 500_000 and not upload.name.endswith('.svg'):
            response['orig_url'] = url
            try:
                response['url'] = get_thumbnail(saved_path, '1000', upscale=False).url
            except OSError:
                pass
    return JsonResponse(response)


@login_required
def make_public(request, *args, **kwargs):
    page = Page.objects.get(id=kwargs['pk'])
    page.public = True
    page.save()
    return HttpResponseRedirect(page.get_online_url())


@login_required
def make_private(request, *args, **kwargs):
    page = Page.objects.get(id=kwargs['pk'])
    page.public = False
    page.save()
    return HttpResponseRedirect(page.get_online_url())


class WikiEdit(PageEditCellView):
    def dispatch(self, request, *args, **kwargs):
        if not request.user or request.user.is_anonymous:
            return HttpResponseForbidden()
        self.page = get_object_or_404(Page, id=kwargs.get('page_pk') or kwargs.get('pk'))
        pages = self.page.get_parents_and_self()
        if not pages[0].slug == 'wiki':
            return HttpResponseForbidden()
        cell = self.get_object()
        new_text = request.POST['c%s-text' % cell.get_reference()]
        if new_text != cell.text:
            cell.text = request.POST['c%s-text' % cell.get_reference()]
            cell.save()
            PageSnapshot.take(self.page, request, comment=_('changed wiki text'))
        return JsonResponse({'err': 0})


edit_wiki = WikiEdit.as_view()

wiki/templates/combo/page_template_sidebar.html
{% extends "base.html" %}
{% load i18n %}

{% block gadjo-js %}
  {{ block.super }}
  <script src="/static/js/combo.wiki.js"></script>
  <link href="/static/css/panik-wiki.css" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block more-user-links %}
  <a href="{% url 'home' %}" class="button icon-home-space"></a>
  <a class="button" href="/wiki/">Accueil Wiki</a>
{% endblock %}

{% block content %}
  <div class="section wiki-section">
    <h3><span class="title">{{ page.title }}</span>
      {% if request.user.is_authenticated %}
        <div id="quickedit">
          <label><input type="checkbox"><span>Mode édition</span></label>
        </div>
      {% endif %}
    </h3>
    {% csrf_token %}

    <div>
      {% placeholder "content" %}

      {% if request.user.is_authenticated or page.interlink_set.all.exists %}
        <div id="page-meta-infos">

          {% if page.interlink_set.all.exists %}
            <p id="backlinks">Pages pointant sur celle-ci :
              {% for interlink in page.interlink_set.all %}
                <a href="{{interlink.cell.page.get_online_url}}">{{ interlink.cell.page.title }}</a>
                {% if not forloop.last %} - {% endif %}
              {% endfor %}</p>
          {% endif %}

          {% if request.user.is_authenticated %}
            {% if page.public %}<p class="public-page">Cette page est accessible publiquement.
              <button data-redirect-url="{% url 'wiki-make-private' pk=page.pk %}" class="link-button">Rendre privée</button>
            {% elif page.groups.all.exists %}
              <p class="private-page">Cette page est visible uniquement pour ces groupes :
                {% for group in page.groups.all %}{{ group }}{% if not forloop.last %}, {% endif %}{% endfor %}
            {% else %}
              <p class="private-page">Cette page est visible uniquement pour les personnes connectées.
                <button data-redirect-url="{% url 'wiki-make-public' pk=page.pk %}" class="link-button">Rendre publique</button>
            {% endif %}
            </p>
          {% endif %}

        </div>

      {% endif %}

    </div>
  </div>
{% endblock %}

wiki/templates/combo/placeholder.html
{% for cell in cells %}
  <div class="cell {{ cell.css_class_names }} {% if cell.slug %}{{cell.slug}}{% endif %}"
       {% if cell.slug %}id="{{cell.slug}}"{% endif %}
       {% if cell.get_cell_type_str == "data_textcell" and request.user.is_authenticated %}data-edit-url="{% url 'wiki-edit' page_pk=page.id cell_reference=cell.get_reference %}"{% endif %}
       {% if cell.ajax_refresh %}
         data-ajax-cell-url="{% url 'combo-public-ajax-page-cell' page_pk=page.id cell_reference=cell.get_reference %}"
         data-ajax-cell-refresh="{{ cell.ajax_refresh }}"
       {% endif %}><div>{% render_cell cell %}</div></div>
{% endfor %}

wiki/templates/wiki/new_page.html
{% extends "base.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{% trans "New Page" %}</h2>
{% endblock %}

{% block content %}
  <form method="post" action="/wiki/newpage/">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="buttons">
      <button class="submit-button">{% trans "Add" %}</button>
      <a class="cancel" href="/wiki/">{% trans "Cancel" %}</a>
    </div>

  </form>
{% endblock %}